# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Conejo Valley MakerSpace
email: info@cvmake.org
description: > # This will be put in the HEAD, so Google can show it.
  The Conejo Valley MakerSpace is where new and experienced Makers
  of all ages connect to work on real projects, share, learn, and have
  fun.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cvmake.github.io" # the base hostname & protocol for your site
twitter_username: cvmake
github_username:  cvmake

# Build settings
markdown: kramdown
